### ISSUE TITLE
如果正则是 #? 回复的命令会是图里面那种触发不了命令

### ISSUE THREAD

**Issue by yongheng1014** [HalcyonAlcedo/karin-plugin-auto-command#1]
![image](https://github.com/HalcyonAlcedo/karin-plugin-auto-command/assets/157875502/4b27fbeb-9aa0-4af8-bb93-b2d331a56c54)

**Comment by HalcyonAlcedo** [comment]
这个回复内容是根据指令的正则表达式经过星火转换而来，具体的内容取决于星火如何对正则表达式进行转换，不是插件能控制的。
